apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: noi-config
  annotations:
    argocd.argoproj.io/sync-wave: "400"
spec:
  destination:
    namespace: noi
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/cp4waiops-gitops 
    path: config/resources
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
