kind: ConfigMap
apiVersion: v1
metadata:
  name: evtmanager-objserv-agg-backup-config
data:
  agg-gate-props-append: ''
  agg-gate-startup-cmd-replace: ''
  agg-gate-tblrep-def-replace: ''
  agg-b-props-append: |
    BackupObjectServer: TRUE
  agg-b-sql-extensions: |
    create database mydb;
    go
    ALTER TABLE alerts.status ADD new_column VARCHAR(50);
    GO
  agg-gate-map-replace: |
    CREATE MAPPING StatusMap
    (
    'Identifier' = '@Identifier' ON INSERT ONLY,
    'Node' = '@Node' ON INSERT ONLY,
    'NodeAlias' = '@NodeAlias' ON INSERT ONLY
    NOTNULL '@Node',
    'Manager' = '@Manager' ON INSERT ONLY,
    'Agent' = '@Agent' ON INSERT ONLY,
    'AlertGroup' = '@AlertGroup' ON INSERT ONLY,
    'AlertKey' = '@AlertKey' ON INSERT ONLY,
    'Severity' = '@Severity',
    'Summary' = '@Summary',
    'StateChange' = '@StateChange',
    'FirstOccurrence' = '@FirstOccurrence' ON INSERT ONLY,
    'LastOccurrence' = '@LastOccurrence',
    'InternalLast' = '@InternalLast',
    'Poll' = '@Poll' ON INSERT ONLY,
    'Type' = '@Type' ON INSERT ONLY,
    'Tally' = '@Tally',
    'ProbeSubSecondId' = '@ProbeSubSecondId',
    'Class' = '@Class' ON INSERT ONLY,
    'Grade' = '@Grade' ON INSERT ONLY,
    'Location' = '@Location' ON INSERT ONLY,
    'OwnerUID' = '@OwnerUID',
    'OwnerGID' = '@OwnerGID',
    'Acknowledged' = '@Acknowledged',
    'Flash' = '@Flash',
    'EventId' = '@EventId' ON INSERT ONLY,
    'ExpireTime' = '@ExpireTime' ON INSERT ONLY,
    'ProcessReq' = '@ProcessReq',
    'SuppressEscl' = '@SuppressEscl',
    'Customer' = '@Customer' ON INSERT ONLY,
    'Service' = '@Service' ON INSERT ONLY,
    'PhysicalSlot' = '@PhysicalSlot' ON INSERT ONLY,
    'PhysicalPort' = '@PhysicalPort' ON INSERT ONLY,
    'PhysicalCard' = '@PhysicalCard' ON INSERT ONLY,
    'TaskList' = '@TaskList',
    'NmosSerial' = '@NmosSerial',
    'NmosObjInst' = '@NmosObjInst',
    'NmosCauseType' = '@NmosCauseType',
    'NmosDomainName' = '@NmosDomainName',
    'NmosEntityId' = '@NmosEntityId',
    'NmosManagedStatus'= '@NmosManagedStatus',
    'NmosEventMap' = '@NmosEventMap',
    'LocalNodeAlias' = '@LocalNodeAlias' ON INSERT ONLY,
    'LocalPriObj' = '@LocalPriObj' ON INSERT ONLY,
    'LocalSecObj' = '@LocalSecObj' ON INSERT ONLY,
    'LocalRootObj' = '@LocalRootObj' ON INSERT ONLY,
    'RemoteNodeAlias' = '@RemoteNodeAlias' ON INSERT ONLY,
    'RemotePriObj' = '@RemotePriObj' ON INSERT ONLY,
    'RemoteSecObj' = '@RemoteSecObj' ON INSERT ONLY,
    'RemoteRootObj' = '@RemoteRootObj' ON INSERT ONLY,
    'X733EventType' = '@X733EventType' ON INSERT ONLY,
    'X733ProbableCause'= '@X733ProbableCause' ON INSERT ONLY,
    'X733SpecificProb' = '@X733SpecificProb' ON INSERT ONLY,
    'X733CorrNotif' = '@X733CorrNotif' ON INSERT ONLY,
    'URL' = '@URL' ON INSERT ONLY,
    'ExtendedAttr' = '@ExtendedAttr' ON INSERT ONLY,
    'ServerName' = '@ServerName' ON INSERT ONLY,
    'ServerSerial' = '@ServerSerial' ON INSERT ONLY,
    'BSM_Identity' = '@BSM_Identity'
    );

    CREATE MAPPING JournalMap
    (
    'KeyField' = TO_STRING(STATUS.SERIAL) + ":" +
    TO_STRING('@UID') + ":" +
    TO_STRING('@Chrono') ON INSERT ONLY,
    'Serial' = STATUS.SERIAL,
    'Chrono' = '@Chrono',
    'UID' = TO_INTEGER('@UID'),
    'Text1' = '@Text1',
    'Text2' = '@Text2',
    'Text3' = '@Text3',
    'Text4' = '@Text4',
    'Text5' = '@Text5',
    'Text6' = '@Text6',
    'Text7' = '@Text7',
    'Text8' = '@Text8',
    'Text9' = '@Text9',
    'Text10' = '@Text10',
    'Text11' = '@Text11',
    'Text12' = '@Text12',
    'Text13' = '@Text13',
    'Text14' = '@Text14',
    'Text15' = '@Text15',
    'Text16' = '@Text16'
    );

    CREATE MAPPING DetailsMap
    (
    'KeyField' = '@Identifier' + '####' +
    TO_STRING('@Sequence') ON INSERT ONLY,
    'Identifier' = '@Identifier',
    'AttrVal' = '@AttrVal',
    'Sequence' = '@Sequence',
    'Name' = '@Name',
    'Detail' = '@Detail'
    );

    CREATE MAPPING IducMap
    (
    'ServerName' = '@ServerName' ON INSERT ONLY,
    'AppName' = '@AppName',
    'AppDesc' = '@AppDesc' ON INSERT ONLY,
    'ConnectionId' = '@ConnectionId' ON INSERT ONLY,
    'LastIducTime' = '@LastIducTime'
    );
